### ISSUE TITLE
Change all Sirupsen to sirupsen

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#106]
Ref
- [x] https://github.com/containerd/containerd/issues/1266;
- [x] https://github.com/moby/moby/pull/34272;
- [x] https://github.com/kubernetes-incubator/cri-o/issues/712.

We should change vendored `Sirupsen` to `sirupsen` after dependencies are resolved.

**Comment by mikebrow** [comment]
Yeah problem is some folks have moved and some have not leaving us in a golang black hole.

**Comment by Random-Liu** [comment]
`docker/docker/pkg/signal` has removed the logrus usage, we could upgrade docker version to get rid of that.
