### ISSUE TITLE
boilerplate verification is needed.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#11]
The initial Makefile is merged in https://github.com/kubernetes-incubator/cri-containerd/pull/7.

Currently, we already have `lint` and `fmt` verification. We need a boilerplate verification.

Ref https://github.com/kubernetes/repo-infra.

**Comment by heartlock** [comment]
@Random-Liu How about reusing  [repo-infra](https://github.com/kubernetes/repo-infra) like [cri-tools](https://github.com/kubernetes-incubator/cri-tools)?  and use `lint` and `fmt` verification in repo-infra.

**Comment by mikebrow** [comment]
repo-infra currently has some issues.. cri-tools isn't using it via vendor it has it's own copy... 

Not sure of the benefits here just yet.

**Comment by Random-Liu** [comment]
@heartlock Since, repo-infra are just a group of script, I don't think we could vendor them anyway. We have to copy and rewrite them. :)

For the boilerplate verification, I think we could reuse it if it works similar with https://github.com/kubernetes/kubernetes/tree/master/hack/boilerplate.

**Comment by mikebrow** [comment]
^ agreed. I planned on working this Friday after dockercon

**Comment by eparis** [comment]
actually they can and are vendored. all of the scripts can run from inside vendor. if they don't work for you, fix them. the main kube repo will be converted one of these days.

**Comment by eparis** [comment]
I think you'll find the external-provisioner using it as a submodule and the service catalog group using it as vendor if you need examples.

**Comment by mikebrow** [comment]
for the go tools it feels odd to vendor what amounts to configuration options/choices for running lint... I opened up an issue a few days ago with some questions, haven't received comments, it's the only and first issue ever filed in the repo. :-) I'll take a look at the boilerplate testing code soon.

Cheers.

**Comment by Random-Liu** [comment]
> actually they can and are vendored. all of the scripts can run from inside vendor. if they don't work for you, fix them. the main kube repo will be converted one of these days.

Hm, can we use godep to vendor script project?

**Comment by mikebrow** [comment]
The readme for repo-infra says "This repository can be used via some golang "vendoring" mechanism (such as glide), or it can be used via git subtree."  @Random-Liu unless you want to use glide.. I might just subtree repo-infra into hack/repo-infra

**Comment by Random-Liu** [comment]
Close this one since this is added. @mikebrow Thanks a lot!
