### ISSUE TITLE
Put containerd-shim into pod cgroup.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#118]
We should put containerd-shim into pod cgroup, so that we could charge the resource usage to pod instead.

Ref https://github.com/containerd/containerd/issues/1032 and https://github.com/containerd/containerd/pull/1134.

/cc @lanchongyizu

**Comment by Random-Liu** [comment]
@lanchongyiju Have you got time to work on this? If not, I could help. :)

**Comment by lanchongyizu** [comment]
@Random-Liu Yes, I am getting familiar with the code.

**Comment by Random-Liu** [comment]
@lanchongyizu Any luck?

**Comment by Random-Liu** [comment]
Hm, seems that @lanchongyizu is not here. :p 

@miaoyq @yanxuean Are you interested in this?

**Comment by abhinandanpb** [comment]
@Random-Liu I can take care of this

**Comment by yanxuean** [comment]
It seem that we have to look for other :)

**Comment by Random-Liu** [comment]
@yanxuean How about this one? :) https://github.com/kubernetes-incubator/cri-containerd/issues/182

**Comment by yanxuean** [comment]
ok，I study the  containerd  first

**Comment by miaoyq** [comment]
@Random-Liu I am glad to accept the new task.

**Comment by lanchongyizu** [comment]
@Random-Liu I am working on it, but I encountered some problems, and I have emailed you for help.

**Comment by Random-Liu** [comment]
@lanchongyizu Hm? I just checked my inbox, and didn't see your email, weird. :/

**Comment by Random-Liu** [comment]
Hm, saw it, NVM. :p Let me see.
