### ISSUE TITLE
A practical way to create a Kubernetes cluster.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#122]
We need to design, implement and document a practical way to create a Kubernetes cluster using containerd as container runtime.

`kubeadm` seems to be the way to go, and https://www.projectatomic.io/blog/2017/06/using-kubeadm-with-cri-o/ is very good reference.

We can start to run some cluster e2e test after this is done.

/cc @kubernetes-incubator/maintainers-cri-containerd

**Comment by ijc** [comment]
FYI I have used `kubeadm` along with `cri-containerd` in the context of [linuxkit/projects/kubernetes](https://github.com/linuxkit/linuxkit/tree/master/projects/kubernetes) and it works, at least as far as I've kicked the tyres. I'm due to clean up those patches any day now.

**Comment by Random-Liu** [comment]
@ijc Cool! Will you have a brief instruction about how to do that? I haven't got time to figure this out yet. :)

**Comment by ijc** [comment]
For me it was just a case of adding
```
+             --container-runtime=remote \
+             --container-runtime-endpoint=unix:///var/run/cri-containerd.sock \
```
To [the script which launches `kubelet`](https://github.com/linuxkit/linuxkit/blob/master/projects/kubernetes/kubernetes/kubelet.sh).

I'm working on raising a LinuxKit PR today.

**Comment by ijc** [comment]
FYI https://github.com/linuxkit/linuxkit/pull/2400 although other than what I wrote above there isn't much which isn't specific to the linuxkit pieces. I'm also @ijc on the docker community slack (I'm on #containerd and #linuxkit among other channels) if you want to chat about it.

**Comment by Random-Liu** [comment]
I think we could close this one. We now have an ansible playbook and a getting start document for bringing up a cluster.
