### ISSUE TITLE
The parameters of InitCNI should be filled in reverse order in NewCRIContainerdService function

### ISSUE THREAD

**Issue by yanxuean** [kubernetes-incubator/cri-containerd#131]
In InitCNI, the first parameter "pluginDir " means the path of cni config file. 
"cniDirs"  means the path of bin.

```
func NewCRIContainerdService(containerdEndpoint, rootDir, networkPluginBinDir, networkPluginConfDir,
	streamAddress, streamPort string) (CRIContainerdService, error) {
        ......
        netPlugin, err := ocicni.InitCNI(networkPluginBinDir, networkPluginConfDir)     <--here
	

func InitCNI(pluginDir string, cniDirs ...string) (CNIPlugin, error) {
	plugin := probeNetworkPluginsWithVendorCNIDirPrefix(pluginDir, cniDirs, "")
```

**Comment by yanxuean** [comment]
If there is a need, I can help on this.

**Comment by Random-Liu** [comment]
@yanxuean You are correct. Those 2 flags are in reverse order, but since the default configurations are also in reverse order, the test could pass till now. Thanks for finding it out!

> If there is a need, I can help on this.

Sure. Feel free to send out a PR. Thanks!

**Comment by Random-Liu** [comment]
Assigned to you. :) @yanxuean
