### ISSUE TITLE
Disable Pid namespace sharing.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#133]
Kubernetes enabled Pid namespace sharing inside a pod with Docker 1.13+.

However, some customers reported that they could not run their container, because their containers made assumptions about the pid 1.

Before resolving this issue, we could not use pid namespace sharing in production. In cri-containerd, we should also disable it by default, and probably introduce a flag to enable it.

**Comment by yanxuean** [comment]
Does anyone do this job?

**Comment by Random-Liu** [comment]
@yanxuean Sorry. I just saw your comment. :p
