### ISSUE TITLE
AllowPrivilegeEscalation test is failing

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#166]
https://travis-ci.org/kubernetes-incubator/cri-containerd/jobs/267875959
```
[91m[1mâ€¢ Failure [328.340 seconds][0m
[k8s.io] Security Context
[90m/home/travis/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:668[0m
  when creating containers with AllowPrivilegeEscalation
  [90m/home/travis/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/security_context_test.go:434[0m
    [91m[1mshould not allow privilege escalation when false [It][0m
    [90m/home/travis/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/security_context_test.go:425[0m

    [91mwait for pod "alpine-nnp-false-914cdbfe-88a6-11e7-8c7b-42010a0a145e" to success
    Expected success, but got an error:
        <*errors.errorString | 0xc420b490f0>: {
            s: "Gave up after waiting 5m0s for pod \"alpine-nnp-false-914cdbfe-88a6-11e7-8c7b-42010a0a145e\" to be \"success or failure\"",
        }
        Gave up after waiting 5m0s for pod "alpine-nnp-false-914cdbfe-88a6-11e7-8c7b-42010a0a145e" to be "success or failure"[0m

    /home/travis/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/pods.go:202
```

@miaoyq

**Comment by Random-Liu** [comment]
You could run the test locally by running:
`make test-e2e-node FOCUS=AllowPrivilegeEscalation`

**Comment by Random-Liu** [comment]
Docker passes `NoNewPrivileges` no matter the container is privileged or not, we should do the same. This is not cause of the test failure, but track it down here.

**Comment by miaoyq** [comment]
@Random-Liu Thanks for your instruction, but `NoNewPrivileges` should be `false` if container is privileged according to the proposal of  [NoNewPrivileges](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/no-new-privs.md#pod-security-policy-changes)
Below is a table defining the default behavior at the pod security policy level:

| allowPrivilegeEscalation setting | uid = 0 or unset   | uid != 0           | privileged/CAP_SYS_ADMIN |
|----------------------------------|--------------------|--------------------|--------------------------|
|  nil                             | no_new_privs=true  | no_new_privs=false | no_new_privs=false       |
|  false                           | no_new_privs=true  | no_new_privs=true  | no_new_privs=false       |
|  true                            | no_new_privs=false | no_new_privs=false | no_new_privs=false       |

**Comment by Random-Liu** [comment]
@miaoyq Nice chart! :)

Yeah, but Kubelet has made the decision for us, e.g. we don't need to check whether uid is 0 or not, and set no_new_privs in cri-containerd. :)

So at least in this area, I feel like we could pass through whatever kubelet gives us, and let kubelet make the decision.

**Comment by miaoyq** [comment]
@Random-Liu  Make sense, I will fix this. : )

**Comment by Random-Liu** [comment]
@miaoyq Thanks! I've included the thing I mentioned in https://github.com/kubernetes-incubator/cri-containerd/pull/168.

But please fix the test. :P I haven't got time to figure out what is wrong.

**Comment by miaoyq** [comment]
@Random-Liu  OK

**Comment by miaoyq** [comment]
@Random-Liu The problem is that "NoNewPrivs" is admitted only if the runtime is docker or rkt in kubelet.
I have opened a issue in kubernetes, see [here](https://github.com/kubernetes/kubernetes/issues/51319)

**Comment by Random-Liu** [comment]
OK... Once again... Thanks for debugging! I'll see how we could deal with this.

**Comment by mikebrow** [comment]
starting to feel like maybe we should do a grep of docker across the repo and start opening issues :-)

**Comment by Random-Liu** [comment]
Sent https://github.com/kubernetes/kubernetes/pull/51347 to fix this.

We should update CRI once first for AppArmor. @mikebrow Would you like to do that in your PR?

**Comment by Random-Liu** [comment]
https://github.com/kubernetes/kubernetes/pull/51347 still doesn't fix this issue. We need https://github.com/kubernetes/kubernetes/pull/51404.

@miaoyq Thanks for catching this.

**Comment by Random-Liu** [comment]
This is fixed after updating kubernetes. @miaoyq Thanks for working on this!
