### ISSUE TITLE
We need the CNI plugin fix https://github.com/kubernetes-incubator/cri-o/pull/806

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#180]
We should either push that fix to cri-o/ocicni, or maintain a branch our own.

/cc @abhinandanpb

**Comment by Random-Liu** [comment]
@miaoyq Would you like to do this? :)

**Comment by miaoyq** [comment]
@Random-Liu OK,  I will do this.

**Comment by Random-Liu** [comment]
@miaoyq Thanks! :)

**Comment by miaoyq** [comment]
@Random-Liu  I have sent a PR for in [cri-o/ocicni](https://github.com/cri-o/ocicni/pull/2), I will fix this after merged.
