### ISSUE TITLE
Support mount propagation.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#185]
We should support mount propagation after CRI supports it https://github.com/kubernetes/kubernetes/pull/46444.

**Comment by Random-Liu** [comment]
kubernetes/kubernetes#46444 is going to be merged soon. We should update kubernetes version and support it after it is merged.

**Comment by Random-Liu** [comment]
The Kubernetes PR has been merged. We should add the mount propagation support.

Feel free to grab this one if you are interested @yanxuean @miaoyq. :)

**Comment by yanxuean** [comment]
I don't understand this PR, Can you give me more detail.

**Comment by miaoyq** [comment]
@Random-Liu @yanxuean  I will work for this.

**Comment by miaoyq** [comment]
@Random-Liu  First of all, we should sync `k8s.io/kubernetes/staging/src/k8s.io/api` to `k8s.io/api` project.
Cloud you help me sync this?  I don't have permission.

**Comment by Random-Liu** [comment]
@miaoyq Hm, their bot is broken, we may have to wait for them to sync.

**Comment by Random-Liu** [comment]
@miaoyq @yanxuean I've sent Collaborators invitation to you, so that I could assign issue to you. :)

**Comment by miaoyq** [comment]
@Random-Liu  Looks like we don't need to update `api`, the change is used in `k8s`.

I have created a pr for this.
