### ISSUE TITLE
We should make sandbox container image configurable.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#191]
The default sandbox image is `gcr.io/google_containers/pause`. However, someone may want to use another one. Especially for people in China, they could not access `gcr.io` for some reason, :p 

We should make it configurable.

This is the way to unblock your work @lanchongyizu.

**Comment by yanxuean** [comment]
I can help on this.

**Comment by Random-Liu** [comment]
@yanxuean Let @lanchongyizu try this first. He just encountered this problem, and reported to me. I think he's on this now.

We have other issues need help, too. :)

**Comment by yanxuean** [comment]
ok ：）

**Comment by Random-Liu** [comment]
This has been fixed. Close.
