### ISSUE TITLE
using ro snapshot for rootfs fails if all required mount points are not present.

### ISSUE THREAD

**Issue by ijc** [kubernetes-incubator/cri-containerd#220]
Trying to run the [sock shop demo](https://github.com/microservices-demo/microservices-demo) fails since several of the ro rootfs images lack various required bind-mount targets such as `/etc/hosts`. This produces (I've substituted our the long ids and manually wrapper for readability):
```
container_linux.go:265: starting container process caused \
    "process_linux.go:348: container init caused \
    \"rootfs_linux.go:57: mounting \\\"/var/lib/cri-containerd/sandboxes/«sb-id»/hosts\\\" to \
    rootfs \\\"/run/containerd/io.containerd.runtime.v1.linux/k8s.io/«ctr-id»/rootfs\\\" at \
    \\\"/run/containerd/io.containerd.runtime.v1.linux/k8s.io/«ctr-id»/rootfs/etc/hosts\\\" caused
    \\\"open /run/containerd/io.containerd.runtime.v1.linux/k8s.io/«ctr-id»/rootfs/etc/hosts: \
    read-only file system\\\"\""
```
This is `runc` checking if the mount point exists (it doesn't) and then failing to `touch` it to create it (see [runc code](https://github.com/opencontainers/runc/blob/master/libcontainer/rootfs_linux.go#L241)).

This example is from `docker.io/library/mongo:latest` but I believe this will be quite common because Docker contains [code](https://github.com/moby/moby/blob/master/daemon/initlayer/setup_unix.go#L19) which creates an "init layer" in order to provide these mount points if they don't exist so it is easy to omit them and not notice.

containerd had some code to produce an initlayer but it was removed in https://github.com/containerd/containerd/pull/1348. @stevvooe is proposing to reinstate them in https://github.com/containerd/containerd/pull/1477 so one (good) option is to make use of that.

An alternative would be to stop using `containerd.WithNewSnapshotView()` for ro containers and always use `containerd.WithNewSnapshot()` but instruct runc to make the rootfs ro in the bundle config. Then runc should be able to make the mount points as necessary before it makes the rootfs readonly. This has the downside of making some files magically appear in the diff of the rootfs, which would be bad in some usecases (e.g. build) but I think is acceptable enough for the cri-containerd usecase (at least for now).

I think the preference should be to reintroduce init layer construction in containerd (i.e. https://github.com/containerd/containerd/pull/1477) and use that, so just mentioning the alternative for completeness/fallback.

NB @crosbymichael tells me that more work would be needed on the `runc` side to have it correctly handle being given a ro rootfs (it handles taking a rw and making it ro correctly though).

/cc @Random-Liu @crosbymichael @stevvooe @dmcgowan

**Comment by crosbymichael** [comment]
An init layer still won't fix everything.  User bind mounts will fail if the dir does not exist and you don't have spec information at rootfs create time to create all these dirs, atleast not usually.

The way docker works today is that it always provides RW to runc and then after runc has finished setting up the rootfs, it remounts / as RO.

**Comment by ijc** [comment]
Thanks @crosbymichael. That seems to me to shift the balance towards just doing the alternative I suggested in the first instance.

We could also consider whether to _also_ add an init layer longer term.

**Comment by dmcgowan** [comment]
I always wanted init layers to be a choice by the client, but I was hoping that the pure runtimes (no building) would not be concerned with the potential side effects of these files getting created. Ideally the base images would include this "default" set of directories and files that are normally needed to run linux containers. In the case where they do get created on container startup and that runtime gets diffed (such as a checkpoint), it seems accurate to me that the diff would fully represent the container's filesystem, even if the user did not explicitly create those files. I can see how this could be surprising in some build cases, but let a builder application make that decision for itself. That is my 2¢

**Comment by Random-Liu** [comment]
> An alternative would be to stop using containerd.WithNewSnapshotView() for ro containers and always use containerd.WithNewSnapshot() but instruct runc to make the rootfs ro in the bundle config. Then runc should be able to make the mount points as necessary before it makes the rootfs readonly. This has the downside of making some files magically appear in the diff of the rootfs, which would be bad in some usecases (e.g. build) but I think is acceptable enough for the cri-containerd usecase (at least for now).

So are we suggesting to do this? SGTM, given that we don't support build. This seems more simple and generic.

But I saw that https://github.com/containerd/containerd/pull/1477 was merged, so what is our plan?

**Comment by ijc** [comment]
I plan to raise a PR to switch to `containerd.WithNewSnapshot()` unconditionally, it seems that is both necessary and sufficient for this use case, whether we then want to add an init layer as well I'm not sure about but that can be a separate conversation AFAICT.
