### ISSUE TITLE
Add truncindex for sandbox, container and image store.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#222]
In Kubernetes, we never pass trunc index via CRI.

However, trunc index makes CLI tool easier to use, e.g. `crictl` does assume trunc index should work.

We should reuse docker https://github.com/moby/moby/blob/master/pkg/truncindex/truncindex.go, and add trunc index support in sandbox, container and image store: https://github.com/kubernetes-incubator/cri-containerd/tree/master/pkg/store/image

**Comment by Random-Liu** [comment]
Anyone feel free to pick up this if you are interested. :)

**Comment by yanxuean** [comment]
I would like to try it.  Are there deadline?  @Random-Liu

**Comment by Random-Liu** [comment]
Nope! Take your time.

**Comment by yanxuean** [comment]
Where do we add test case? Look like we should not add it in cri-tools  and unit tese.
@Random-Liu

**Comment by Random-Liu** [comment]
@yanxuean What kind of test case do you mean? For this feature, I think unit test is enough. :)

**Comment by Random-Liu** [comment]
Since, this means that `id` passed to CRI may be different from the real id. So please make sure all CRI functions are using ID from store instead of the id passed-in directly.

**Comment by yanxuean** [comment]
Ithink we should test it like it's user(e.g. crictl).Do you mean wo only test store object?
But I modified sandboxList function because there is sandboxId in filter too :)

**Comment by Random-Liu** [comment]
@yanxuean Yeah, for now only store object. Because this behavior is not actually defined in CRI, I don't think we want to add it to CRI validation test.

**Comment by yanxuean** [comment]
ok. Agree with you.
Should we prohibit it in crictl?
```bash
# crictl sandboxes --help
NAME:
   crictl sandboxes - List sandboxes

USAGE:
   crictl sandboxes [command options] [arguments...]

OPTIONS:
   --id value                filter by pod sandbox id
   --state value, -s value   filter by pod sandbox state
   --label value, -l value   filter by key=value label
   --verbose, -v             show verbose info for sandboxes
   --quiet                   list only sandbox IDs
   --output value, -o value  Output format, One of: json|yaml|table
```

**Comment by Random-Liu** [comment]
> ok. Agree with you. Should we prohibit it in crictl?

We could add the truncindex for filter in another PR. We do need it.
