### ISSUE TITLE
Add a default config file which put most things into comment with description.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#226]
@yanxuean

**Comment by Random-Liu** [comment]
Ref https://github.com/kubernetes-incubator/cri-containerd/pull/200

**Comment by yanxuean** [comment]
> @yanxuean Could we add a default config in another PR? Possibly like default apache config, which puts most things into comment, but user could easily understand how to use the config, and uncomment
and modify lines they need.

I agree with you. I originally planed to output deault toml example like containerd(e.g.   containerd  config  default).  But cri-containerd has not used urfave/cli. I'm thinking a good way for it.

**Comment by yanxuean** [comment]
Do you think about  adding a arg "--print-default-toml" like "--version"?
One can get default toml by type "cri-containerd  --print-default-toml  > xxx.toml".

**Comment by Random-Liu** [comment]
@yanxuean Cool, that's a better solution.

**Comment by Random-Liu** [comment]
@yanxuean Actually, since `cri-containerd` is a simple daemon, we are not using `urfave/cli`.

I think a flag `--default-config` is good enough for now.
