### ISSUE TITLE
Switch to containerd extension

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#251]
Ref https://github.com/containerd/containerd/pull/1378.

We should switch to new containerd extension before 1.0.0-alpha.0, so as to avoid backward compatibility issue.

**Comment by Random-Liu** [comment]
containerd/containerd#1378 is merged.
We could do this now.

**Comment by yanxuean** [comment]
I can help on this.    @Random-Liu

**Comment by Random-Liu** [comment]
@yanxuean Sure! Thanks!
Please note that:
1) We need to finish this this week. Because next week, we are planning to cut a release.
2) This may need some rebase after https://github.com/kubernetes-incubator/cri-containerd/pull/209 is merged.

**Comment by yanxuean** [comment]
ok, no problem.  @Random-Liu
