### ISSUE TITLE
Travis Trusty doesn't support apparmor

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#268]
AppArmor is disabled in travis trusty, it means that all apparmor tests are skipped in travis.

It's fine for now, because I run the test myself, and they do pass on OS distro supporting AppArmor.

However, we may still want to track this issue, and we should be able to fix after we start testing in Kubernetes test infrastructure.

**Comment by Random-Liu** [comment]
Ref https://github.com/kubernetes-incubator/cri-containerd/pull/267

**Comment by mikebrow** [comment]
Thanks for testing and tracking this!

**Comment by Random-Liu** [comment]
@mikebrow Yeah, we'll be testing this on the ubuntu image and COS image used in Kubernetes test infra.

**Comment by mikebrow** [comment]
yeah, should probably move CI up to a later distro

**Comment by Random-Liu** [comment]
I think we could close this one now. We already run node e2e in Kubernetes test infrastructure, and the images used there both have apparmor support.
