### ISSUE TITLE
What is initial version of containerd that cri-containerd supports? 

### ISSUE THREAD

**Issue by allencloud** [kubernetes-incubator/cri-containerd#269]
Hi, All,

What kind of containerd's version does cri-containerd support?

We know that docker-ce and docker-ee are vendoring container 0.2.3 to finish container management. While I found that there are lots of changes between container 0.2.3 and the coming container 1.0.0, especially on the image side or something else.

Then my question is that, for a CRI implementation, to upper side it should be compatible with CRI, to lower side it should be compatible with containerd API, the what version of containerd will cri-containerd support?

I see that in the `vendor.conf` https://github.com/kubernetes-incubator/cri-containerd/blob/master/vendor.conf#L5, the commit ID is the latest.

Then for the legacy docker-ce or older docker, does it mean we can not utilize the containerd directly in kubernetes via cri-containerd?

**Comment by crosbymichael** [comment]
1.0 containerd API

**Comment by mikebrow** [comment]
This project is for running kubernetes on top of containerd 1.0 and above. If you are interested in kubernetes on docker (which is using the other release of containerd (legacy isn't really the right word here)), see the kubernetes CRI based docker shim over here: https://github.com/kubernetes/kubernetes/tree/master/pkg/kubelet/dockershim

**Comment by Random-Liu** [comment]
> Then my question is that, for a CRI implementation, to upper side it should be compatible with CRI, to lower side it should be compatible with containerd API, the what version of containerd will cri-containerd support?

Yeah, as is mentioned by @crosbymichael and @mikebrow, we are using containerd 1.0 API.

> I see that in the vendor.conf https://github.com/kubernetes-incubator/cri-containerd/blob/master/vendor.conf#L5, the commit ID is the latest.

We'll update vendor to a specific containerd tag, after containerd is stabilized. Currently, we still have to grab newest commit to include fixes we need.

> Then for the legacy docker-ce or older docker, does it mean we can not utilize the containerd directly in kubernetes via cri-containerd?

Docker will also switch to containerd 1.0. They will firstly switch the container management part, which I heard is going to happen by the end of this year. And they will switch the image management part probably next year.

**Comment by crosbymichael** [comment]
Docker already has a PR out to integrate containerd 1.0 that is being tested. 

https://github.com/moby/moby/pull/34895

**Comment by allencloud** [comment]
Thanks a lot for all of your detailed explanations  @crosbymichael @mikebrow @Random-Liu 
Closing this.
