### ISSUE TITLE
Integrate with kubernetes network plugin.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#27]
CRI expects the runtime to handle container networking.

As is expected, containerd itself doesn't provide container networking. We should integrate cri-containerd with kubernetes network plugin to initialize the network namespace.

Things need to do:
1) Add flags for network plugin settings and initialize network plugin in cri-containerd. (See https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/docker_service.go#L197-L204)
2) Implement interface needed by network plugin, include `namespaceGetter` and `portMappingGetter`. (See https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/docker_service.go#L119-L137)
3) Setup and teardown network when run/stop pod sandbox. (See https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/docker_sandbox.go#L128)

/cc @xlgao-zju

**Comment by Random-Liu** [comment]
@xlgao-zju The sandbox lifecycle is merged. We could start this work.

**Comment by xlgao-zju** [comment]
@Random-Liu Yes, I am working on it.
