### ISSUE TITLE
Maintain resolv.conf for pod.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#28]
Previously, Docker maintains a resolv.conf for containers sharing the same network namespace.

Now, when using containerd, we need to do these ourselves. We need to:
1) Maintain a resolv.conf when creating/removing sandbox if not using `HostNetwork`. And initialize resolv.conf with `DNSOptions` in `PodSandboxConfig`.
2) Bind mount the resolv.conf into each container.

This logic is similar with cri-o. (See https://github.com/kubernetes-incubator/cri-o/blob/master/server/sandbox_run.go#L144-L159)

/cc @xlgao-zju

**Comment by Crazykev** [comment]
Since #22 has been merged, I'll get this done ASAP.

**Comment by Crazykev** [comment]
@Random-Liu To implement this, we need to maintain `resolv.conf` file for each pod(expect for hostNetwork pod) and `resolvPath` for this file. This `resolvPath` is related with on-disk layout(not implemented yet), do you have any suggestion or preference on this? Thanks.

**Comment by Random-Liu** [comment]
@Crazykev Just put the resolv file into sandbox root. https://github.com/kubernetes-incubator/cri-containerd/blob/master/pkg/server/sandbox_run.go#L91

**Comment by Random-Liu** [comment]
Close this one since the PR is merged, thanks! @Crazykev
