### ISSUE TITLE
Support Privileged.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#29]
`Privileged` is initially a Docker concept. Docker grants a group of permissions and mounts a group of directories into a privileged pod.

In Kubernetes, we should define our own `Privileged` https://github.com/kubernetes/kubernetes/issues/44503. For now, we could do whatever docker is doing.

Things to do:
1) Figure out what docker is doing to `Privileged` container.
2) Do the same in cri-contained.

/cc @heartlock

**Comment by heartlock** [comment]
I will take this task. Wait for #22

**Comment by Random-Liu** [comment]
@heartlock I'll update #22 today, and will try to get it merged this week.

**Comment by Random-Liu** [comment]
FYI, @heartlock The container lifecycle PR is merged. #22

**Comment by heartlock** [comment]
@Random-Liu ok, will do it.

**Comment by Random-Liu** [comment]
@heartlock For the device mapping, you could reference the cri-o implementation. https://github.com/kubernetes-incubator/cri-o/blob/master/server/container_create.go#L68-L93

**Comment by Random-Liu** [comment]
Close this one since the PR is merged.

Thanks @heartlock
