### ISSUE TITLE
Additional work needed on image apis

### ISSUE THREAD

**Issue by mikebrow** [kubernetes-incubator/cri-containerd#32]
1) add config.json image/image.config struct to the resolver helper
2) remaining nit TODOs
3) add auth impl
4) add list filters
5) add name resolution code

**Comment by Random-Liu** [comment]
And we also need to figure out a way to deal with schema 1 image.

**Comment by Random-Liu** [comment]
We also need to figure out how to remove image

**Comment by mikebrow** [comment]
Note how we put it into the store:
c.imageStore.Put(ctx, resolvedImageName, desc)

Delete should be:
c.imageStore.Delete(cox, resolvedImageName)

**Comment by Random-Liu** [comment]
3, 4 are not finished in this issue, but they'll be tracked in https://github.com/kubernetes-incubator/cri-containerd/issues/62.

Close this one.
