### ISSUE TITLE
Update `golang.org/x/sys`

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#333]
Currently, cri-containerd is using a different version of `golang.org/x/sys`.

The reason is that we are also using `docker/pkg/signal` which still relies on the old version containing `unix.SIGUNUSED`.

We should update the version after docker updates it.

**Comment by mikebrow** [comment]
https://github.com/moby/moby/commit/86f080cff0914e9694068ed78d503701667c4c00
