### ISSUE TITLE
Integrate with cadvisor

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#341]
Based on the discussion in today's signode meeting, we still have to integrate containerd with cadvisor, and update kubelet to consume metrics from both CRI and cadvisor.

For the cadvisor integration we don't need the imagefs stats, because kubelet will get that from CRI.
https://docs.google.com/presentation/d/1Os3nyMRBlFuiBLCjPgeaPv6jXylrZW5jiDXJejlA3Wg/edit?usp=sharing

This work needs to:
1) Change cadvisor to be able to monitor containerd stats;
2) Update kubelet to consume stats from both cadvisor and CRI.

**Comment by Random-Liu** [comment]
@abhi

**Comment by abhi** [comment]
Starting on this

**Comment by Random-Liu** [comment]
We should enable summary api node e2e test after this is done, to verify whether this fix.

**Comment by Random-Liu** [comment]
Note that even with this change, we could not provide container log stats, see https://github.com/kubernetes/kubernetes/issues/55905.

We should point it our in the release note.
