### ISSUE TITLE
Support schema 1 manifest.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#35]
Currently, containerd only supports schema 2 manifest.

For cri-containerd, not supporting schema 1 means:
1) Users who are still using schema 1 image could not use cri-containerd integration.
2) Some system container images are still using schema 1 manifest, e.g. pause image.

Regarding to 1), it is fine for our alpha release (this quarter), but it should be fixed before beta (probably the end of the year).

For 2), we need to rebuild our schema 1 system container image.

Ref https://github.com/containerd/containerd/issues/851.

**Comment by Random-Liu** [comment]
This become the bigest blocker for running node e2e test.
Many images used by node e2e test are using schema 1 image.

Except that, other 2 high priority work for testing:
1) Implement container log;
2) ExecSync.

**Comment by crosbymichael** [comment]
What is ExecSync?

**Comment by Random-Liu** [comment]
@crosbymichael It's defined in CRI, https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/cri/v1alpha1/api.proto#L66.

Basically exec a command in container and return result synchronously.

**Comment by Random-Liu** [comment]
@crosbymichael I might mislead your guys, the other 2 items are purely on our side.

**Comment by Random-Liu** [comment]
This is finished in https://github.com/kubernetes-incubator/cri-containerd/pull/81.

Close this one.
