### ISSUE TITLE
Implement CRI Debug API

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#359]
We added the `verbose` option in CRI to make it possible for container runtime to provide more information for debug. https://github.com/kubernetes/kubernetes/pull/53965

We should implement it in cri-containerd.

Functions we need to change:
- [x] ContainerStatus
- [x] PodSandboxStatus
- [x] ImageStatus
- [x] Status

We need to:
1) Take a look at what information is included in today's `docker inspect` and `docker info`, and properly design what debug information we should include in cri-containerd.
2) Add those information in corresponding functions.
3) Change `crictl` to consume the extra information.

**Comment by mikebrow** [comment]
Background issue:
https://github.com/kubernetes/kubernetes/issues/53757

**Comment by weiwei04** [comment]
If there's no one doing this, I can take a try :)

**Comment by mikebrow** [comment]
I've started some work on it.

**Comment by Random-Liu** [comment]
@weiwei04 There will be various issues filed by @mikebrow or me for this in both `cri-containerd` and `cri-tools` repositories.

Feel free to pick one if you are interested. :)

**Comment by Random-Liu** [comment]
Things might be useful for container info:
* container config.
* pid.
* more

**Comment by abhi** [comment]
Starting on this

**Comment by mikebrow** [comment]
hey ok been busy :-)

**Comment by mikebrow** [comment]
"value should be in json format" grr

**Comment by mikebrow** [comment]
ok added:

- container config.
- pid.
- removing state.
- container runtime spec.

The runtime spec has tons of good debug stuff missed in the non verbose.. it although there will be lots of duplicate information as well.

**Comment by mikebrow** [comment]
See https://github.com/kubernetes-incubator/cri-tools/pull/206

**Comment by Random-Liu** [comment]
Add sandbox id in container status. We should add it into CRI eventually, but it's code freeze now.

**Comment by mikebrow** [comment]
A little back link to the pod.. ok I like it.

**Comment by mikebrow** [comment]
Added:
Container Status:

- sandboxID

Pod Status:

- sandboxContainerdPID
- sandboxContainerState
- runtimeSpec
- snapshotter info

**Comment by mikebrow** [comment]
Added:

Image Status:

- image config
- image config descriptor
- image target descriptor
- image digest info for the array of digests

**Comment by mikebrow** [comment]
** ok now that we've got a decent amount of debug info in the verbose mode, we need to go back and add (or consider adding) some group structs for the verbose information. This is because the order for the data in the map is random and might not make as much sense out of order as it would in some defined sequence at least for a group of items.

Eg. "snapshotInfo": { "snapshotKey": ... "snapshotter":... }

**Comment by mikebrow** [comment]
Pod and Image verbose info are ready for final review.

**Comment by mikebrow** [comment]
Image verbose is ready for final review...

**Comment by Random-Liu** [comment]
@mikebrow All done. I think we can close this one.

Can you add a simple document for `crictl`? For https://github.com/kubernetes-incubator/cri-containerd/issues/96

We just need a reference in somewhere in our repo.
It should point out that:
1) We should use `crictl` for debugging cri-containerd.
2) A simple example, e.g. `crictl inspect`.
3) Link to crictl document.
