### ISSUE TITLE
Use `image.IsUnpacked` in containerd.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#361]
In https://github.com/kubernetes-incubator/cri-containerd/pull/358, we need to check whether image is unpacked before container creation.

We could use the new helper function in containerd. https://github.com/containerd/containerd/pull/1668

**Comment by miaoyq** [comment]
I will work on this.

**Comment by miaoyq** [comment]
@yanxuean  have fixed this.
/unassign
/assign @yanxuean

**Comment by yanxuean** [comment]
crash

**Comment by yanxuean** [comment]
Sorry for waste @miaoyq time.
