### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#4]
We should enable travis to run presubmit build and unit test.

**Comment by heartlock** [comment]
I will take this task if it's ok for you. @Random-Liu  Need Makefile and some scripts to power the test.

**Comment by Random-Liu** [comment]
@heartlock Sure! Feel free to take this one.

But you may want to wait for https://github.com/kubernetes-incubator/cri-containerd/issues/3.

**Comment by mikebrow** [comment]
ok will also need some unit tests before we can unit test :-)

**Comment by Random-Liu** [comment]
> ok will also need some unit tests before we can unit test :-) Till we add some tests you can run make lint; make gofmt; and make binaries ...

Yeah, for now, verification and build is enough.

In the future, we need a `make test`.

**Comment by Random-Liu** [comment]
@heartlock The initial `Makefile` is merged. Feel free to add the travis file. :)

**Comment by Random-Liu** [comment]
Close this one since #12 is merged. Thanks! @heartlock
