### ISSUE TITLE
Revert or cleanup https://github.com/kubernetes-incubator/cri-containerd/pull/463

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#468]
We merged https://github.com/kubernetes-incubator/cri-containerd/pull/463 to help debug https://github.com/containerd/containerd/issues/1785.

We should revert or clean it up after https://github.com/containerd/containerd/issues/1785 is fixed.

File this issue to track that.

**Comment by yanxuean** [comment]
I suggest to reserve it.  We spent many time on the issue. Maybe the code is usable for coming issue.

**Comment by yanxuean** [comment]
We can make some test cases to check the service of containerd .
These test cases can use the checkImage and checkSnapshot function.
@mikebrow  WDYT?

**Comment by Random-Liu** [comment]
@yanxuean I don't think we should keep that in the production code path. The extra mount/unmount affects performance.

As for whether we want to add a test for that, I feel like it should be a containerd test instead.
We added it in our code, because we could only reproduce it in our CI. It's not very useful to add a single unit test for that.

**Comment by yanxuean** [comment]
OK, Agree

**Comment by Random-Liu** [comment]
I think we can close this now. @yanxuean

**Comment by yanxuean** [comment]
yes
