### ISSUE TITLE
cri-containerd shouldn't exit when contaienrd exit

### ISSUE THREAD

**Issue by miaoyq** [kubernetes-incubator/cri-containerd#488]
`cri-containerd` and `containerd` are different services, so `cri-containerd` shouldn't exit when `containerd` is not up yet or exit. 
Instead, `cri-containerd` should periodically check if `containerd` is active or not. 
Like kubelet check `container-runtime`.

@kubernetes-incubator/maintainers-cri-containerd   wdyt?

**Comment by Random-Liu** [comment]
@miaoyq This is on purpose.
The reason is here:
https://github.com/kubernetes-incubator/cri-containerd/pull/183

**Comment by miaoyq** [comment]
@Random-Liu  Got it, Thanks.

**Comment by Random-Liu** [comment]
Close this one. :)
