### ISSUE TITLE
Use containerd client.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#49]
Containerd is adding a new client, which will make integration and our unit test much easier.

We should use it after it lands.

https://github.com/containerd/containerd/pull/904

**Comment by mikebrow** [comment]
Looks nice.. will have to see if it does all we need.

**Comment by Random-Liu** [comment]
Just a note here, the so-called `AgentFactory` could be removed after we switch to new containerd client.

**Comment by Random-Liu** [comment]
Given that:
1) The timeframe is pretty tight;
2) Containerd client may miss some features we need, e.g. some image functions.

I propose the following plan:
- [ ] [P0] Upgrade to new containerd **API**, and make it work.
- [ ] [P1] Replace all service clients with "client.service" (containerd expose all services directly).
- [ ] [P0] Cut the alpha.1 release, which I think highly possibly will be our final alpha release version.
- [ ] [P2] Switching each function to use new containerd client one by one.

@kubernetes-incubator/maintainers-cri-containerd 
/cc @crosbymichael @stevvooe

**Comment by Random-Liu** [comment]
Change this to v0.2.0. I don't think we have time to switch to the new client. Making sure we are using new containerd api is good enough for this release.

@mikebrow Let's finish the second step in this release and leave the client switch to next one.
