### ISSUE TITLE
Developer Guide

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#5]
It's too early to add a developer guide, but we should add one in the future when the build and development process is finalized.

**Comment by mikebrow** [comment]
right.. I can update the readme with a basic here's what you do set of notes along with the makefile..

**Comment by Random-Liu** [comment]
We've added document for developer to run test https://github.com/kubernetes-incubator/cri-containerd/blob/master/docs/testing.md, which is most important for now.

Punt the others to 0.2.0.

**Comment by mikebrow** [comment]
sounds good

**Comment by Random-Liu** [comment]
We should update both `README.md` and `testing.md`.
@mikebrow

**Comment by Random-Liu** [comment]
I think our README.md will become our main developer guide. Close this one and focus on updating README.md.
