### ISSUE TITLE
Unable to create sandbox

### ISSUE THREAD

**Issue by ambiknai** [kubernetes-incubator/cri-containerd#520]
Error while creating sandbox
root@cri-master:~# crictl version
```Version:  0.1.0
RuntimeName:  cri-containerd
RuntimeVersion:  1.0.0-beta.0
RuntimeApiVersion:  0.0.0
root@cri-master:~# ```

root@cri-master:~# crictl runs sandbox-config.json
```FATA[0000] run pod sandbox failed: rpc error: code = Unknown desc =failed to setup network for sandbox     "3ad790c715c817d22e6f6df95bf612dbc0ceaf05d2d94f94e62aa4b57234ea57": pods "nginx-sandbox" not found 
```

cat sandbox-config.json
```{
    "metadata": {
        "name": "nginx-sandbox",
        "namespace": "default",
        "attempt": 1,
        "uid": "hdishd83djaidwnduwk28bcsb"
    },
    "linux": {
    }
}
```

**Comment by Random-Liu** [comment]
@ambiknai How did you install cri-containerd? Can you point me which doc did you follow?

It seems to me that your CNI is not installed.

**Comment by ambiknai** [comment]
I followed this doc
[https://github.com/kubernetes-incubator/cri-containerd/blob/master/docs/installation.md](url)

**Comment by Random-Liu** [comment]
That is a document for create a Kubernetes cluster with `kubeadm`. If you follow the whole document including the last step [Bring Up the Cluster](https://github.com/kubernetes-incubator/cri-containerd/blob/master/docs/installation.md#bring-up-the-cluster), you will be able to create sandbox.

The CNI plugin is installed in the last step.

**Comment by ambiknai** [comment]
Yes, I did that as well
```root@cri-master:~# kubectl get pods --all-namespaces
NAMESPACE     NAME                                     READY     STATUS    RESTARTS   AGE
kube-system   calico-etcd-c24xv                        1/1       Running   1          4h
kube-system   calico-kube-controllers-d6c6b9b8-d4sql   1/1       Running   1          4h
kube-system   calico-node-6rkxr                        2/2       Running   3          4h
kube-system   calico-node-k9vqs                        2/2       Running   0          4h
kube-system   etcd-cri-master                          1/1       Running   1          4h
kube-system   kube-apiserver-cri-master                1/1       Running   1          4h
kube-system   kube-controller-manager-cri-master       1/1       Running   1          4h
kube-system   kube-dns-6f4fd4bdf-rnvph                 3/3       Running   0          3h
kube-system   kube-proxy-t2ds9                         1/1       Running   0          4h
kube-system   kube-proxy-vrwkf                         1/1       Running   1          4h
kube-system   kube-scheduler-cri-master                1/1       Running   1          4h```

**Comment by Random-Liu** [comment]
Hm then that’s weird. I’ll take a look tomorrow morning. Thanks for reporting issue!

**Comment by ambiknai** [comment]
Should a pod by name `nginx-sanbox` be present before we do the sandbox creation.Because the error says `pods "nginx-sandbox" not found `

**Comment by miaoyq** [comment]
>cat sandbox-config.json
```
    "metadata": {
        "name": "nginx-sandbox",
        "namespace": "default",
        "attempt": 1,
        "uid": "hdishd83djaidwnduwk28bcsb"
    },
    "linux": {
    }
}
```

Could you remove `"attempt": 1,` and try it again?

**Comment by Random-Liu** [comment]
@ambiknai I think the problem is that: IIRC, calico daemonset watch apiserver to get a list of pods, and apply network configuration based on the pod spec.

If you use `crictl` create a sandbox yourself, there won't be corresponding pod on apiserver, thus calico reports that error.

In fact, we don't recommend user to run `crictl runs` and `crictl create`, those commands are there just for some special debug case. And that's also why we make the command not that easy to use, user need to prepare for a configuration file to create a sandbox/container.

In fact, even you are able to create the sandbox, kubelet will eventually stop and delete it because it doesn't see the corresponding pod on apiserver.

If you just want to try `crictl`, the error is caused by the reason above.
If you just want to try create a pod, use `kubectl` instead. :)

**Comment by ambiknai** [comment]
Thanks @Random-Liu. Closing this issue as my doubts are clarified now.
