### ISSUE TITLE
Rename `container` to `task`

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#79]
The previous `container` concept in containerd is changed to `task`.
In the refactoring PR, I've changed most of them to `task`.

However, there are some left, we should clean them up.

**Comment by mikebrow** [comment]
Yeah I changed the ones that "had" to change vs all of them. I figured just the ones that had to change was sufficient given that it's just a naming convention and container is the common term. But I'm not going to argue it.

**Comment by stevvooe** [comment]
So, the `task` is the running thing and the `container` is the isolation metadata. The only real difference is that we have a name for the processes within a container.

Let me know if you need help on mapping the model.

**Comment by mikebrow** [comment]
@stevvooe thx.. understand what it is.. just not a fan of the term yet. Task is one of those overloaded terms, like container :-)

**Comment by stevvooe** [comment]
We needed to call it something. Providing handles to all the behavior of a container while still calling all of those parts a container was getting unwieldy. We had some period of feedback on the change but didn't receive any better suggestions.

**Comment by mikebrow** [comment]
maybe session.. but I'd not change it now. I'll learn to like it by substituting cmeta or session in my head :-)

**Comment by Random-Liu** [comment]
I think we've finished most of this. Let's close this one.
