### ISSUE TITLE
Add `--version` flag.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#8]
Add cri-containerd version.

We should version cri-containerd based on the repo tag and commit number. The version will be used:
1) As part of the name when building a release package or any docker image in the future.
2) As part of `--version` output.

Refer https://github.com/kubernetes/node-problem-detector/pull/71.

**Comment by cmluciano** [comment]
I will take a stab at a PR

**Comment by Random-Liu** [comment]
@cmluciano Sure. Feel free to pick up this! Thanks a lot! :)
