### ISSUE TITLE
Upgrade containerd api.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#86]
Containerd is still making changes to API, e.g. https://github.com/containerd/containerd/pull/1047, https://github.com/containerd/containerd/pull/1062.

We should upgrade once more after they finalize the api.

**Comment by mikebrow** [comment]
A quick review of 1040 and 1047 they don't look like major changes just some renames.

**Comment by Random-Liu** [comment]
> A quick review of 1040 and 1047 they don't look like major changes just some renames.

Yeah, but without rename, cri-containerd won't work with new containerd because grpc requires both sides using the same package name. :)

**Comment by crosbymichael** [comment]
Ya, we are doing our final API review so we have something consistent and good for the long term where its versioned as well.  Sorry for the churn right now but its best to do this now, before a release, then later.

**Comment by Random-Liu** [comment]
@crosbymichael Yeah, no worry. :)

Just track the api change here, so that we do rebase we have better ideas what need to be changed.

**Comment by crosbymichael** [comment]
When we cut the 1.0 alpha it would be a good time to rebase on it

**Comment by mikebrow** [comment]
main changes:
* rename execution->tasks
* execution/task events are now implemented by a new events service
* all services now have the /v1 suffix

**Comment by Random-Liu** [comment]
@mikebrow Thanks! We could keep updating here, so as to make our future rebase easier.

**Comment by crosbymichael** [comment]
We still have 1-2 API level changes to make before cutting the Alpha.  I'll let you know when we do.

**Comment by mikebrow** [comment]
Work in progress synching up to the containerd/containerd current master commit 4888d40ac7ca94b914c5f37c1f8129eab2df3790

**Comment by mikebrow** [comment]
Moving to the latest commit to pick up some more client apis 
4118a256e9f17199ed2ab647fad6946cc59fcd81
